// Auto-generated from tweakcn community themes.
// Source: https://github.com/jnsahaj/tweakcn/blob/main/utils/theme-presets.ts

import type { ThemePreset } from './presets'

export const TWEAKCN_PRESETS: ThemePreset[] = [
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    colorScheme: 'dark',
    radius: '0.375rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#171717',
      '--foreground': '#e5e5e5',
      '--card': '#262626',
      '--card-foreground': '#e5e5e5',
      '--popover': '#262626',
      '--popover-foreground': '#e5e5e5',
      '--primary': '#3b82f6',
      '--primary-foreground': '#ffffff',
      '--secondary': '#262626',
      '--secondary-foreground': '#e5e5e5',
      '--muted': '#1f1f1f',
      '--muted-foreground': '#a3a3a3',
      '--accent': '#1e3a8a',
      '--accent-foreground': '#bfdbfe',
      '--destructive': '#ef4444',
      '--border': '#404040',
      '--input': '#404040',
      '--ring': '#3b82f6',
    },
    lightVars: {
      '--background': '#ffffff',
      '--foreground': '#333333',
      '--card': '#ffffff',
      '--card-foreground': '#333333',
      '--popover': '#ffffff',
      '--popover-foreground': '#333333',
      '--primary': '#3b82f6',
      '--primary-foreground': '#ffffff',
      '--secondary': '#f3f4f6',
      '--secondary-foreground': '#4b5563',
      '--muted': '#f9fafb',
      '--muted-foreground': '#6b7280',
      '--accent': '#e0f2fe',
      '--accent-foreground': '#1e3a8a',
      '--destructive': '#ef4444',
      '--border': '#e5e7eb',
      '--input': '#e5e7eb',
      '--ring': '#3b82f6',
    },
  },
  {
    id: 'violet-bloom',
    name: 'Violet Bloom',
    colorScheme: 'dark',
    radius: '1.4rem',
    fontDisplay: "Lora, serif",
    fontBody: "Plus Jakarta Sans, sans-serif",
    vars: {
      '--background': '#1a1b1e',
      '--foreground': '#f0f0f0',
      '--card': '#222327',
      '--card-foreground': '#f0f0f0',
      '--popover': '#222327',
      '--popover-foreground': '#f0f0f0',
      '--primary': '#8c5cff',
      '--primary-foreground': '#ffffff',
      '--secondary': '#2a2c33',
      '--secondary-foreground': '#f0f0f0',
      '--muted': '#2a2c33',
      '--muted-foreground': '#a0a0a0',
      '--accent': '#1e293b',
      '--accent-foreground': '#79c0ff',
      '--destructive': '#f87171',
      '--border': '#33353a',
      '--input': '#33353a',
      '--ring': '#8c5cff',
    },
    lightVars: {
      '--background': '#fdfdfd',
      '--foreground': '#000000',
      '--card': '#fdfdfd',
      '--card-foreground': '#000000',
      '--popover': '#fcfcfc',
      '--popover-foreground': '#000000',
      '--primary': '#7033ff',
      '--primary-foreground': '#ffffff',
      '--secondary': '#edf0f4',
      '--secondary-foreground': '#080808',
      '--muted': '#f5f5f5',
      '--muted-foreground': '#525252',
      '--accent': '#e2ebff',
      '--accent-foreground': '#1e69dc',
      '--destructive': '#e54b4f',
      '--border': '#e7e7ee',
      '--input': '#ebebeb',
      '--ring': '#000000',
    },
  },
  {
    id: 't3-chat',
    name: 'T3 Chat',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#221d27',
      '--foreground': '#d2c4de',
      '--card': '#2c2632',
      '--card-foreground': '#dbc5d2',
      '--popover': '#100a0e',
      '--popover-foreground': '#f8f1f5',
      '--primary': '#a3004c',
      '--primary-foreground': '#efc0d8',
      '--secondary': '#362d3d',
      '--secondary-foreground': '#d4c7e1',
      '--muted': '#28222d',
      '--muted-foreground': '#c2b6cf',
      '--accent': '#463753',
      '--accent-foreground': '#f8f1f5',
      '--destructive': '#301015',
      '--border': '#3b3237',
      '--input': '#3e343c',
      '--ring': '#db2777',
    },
    lightVars: {
      '--background': '#faf5fa',
      '--foreground': '#501854',
      '--card': '#faf5fa',
      '--card-foreground': '#501854',
      '--popover': '#ffffff',
      '--popover-foreground': '#501854',
      '--primary': '#a84370',
      '--primary-foreground': '#ffffff',
      '--secondary': '#f1c4e6',
      '--secondary-foreground': '#77347c',
      '--muted': '#f6e5f3',
      '--muted-foreground': '#834588',
      '--accent': '#f1c4e6',
      '--accent-foreground': '#77347c',
      '--destructive': '#ab4347',
      '--border': '#efbdeb',
      '--input': '#e7c1dc',
      '--ring': '#db2777',
    },
  },
  {
    id: 'twitter',
    name: 'Twitter',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#000000',
      '--foreground': '#e7e9ea',
      '--card': '#17181c',
      '--card-foreground': '#d9d9d9',
      '--popover': '#000000',
      '--popover-foreground': '#e7e9ea',
      '--primary': '#1c9cf0',
      '--primary-foreground': '#ffffff',
      '--secondary': '#f0f3f4',
      '--secondary-foreground': '#0f1419',
      '--muted': '#181818',
      '--muted-foreground': '#72767a',
      '--accent': '#061622',
      '--accent-foreground': '#1c9cf0',
      '--destructive': '#f4212e',
      '--border': '#242628',
      '--input': '#22303c',
      '--ring': '#1da1f2',
    },
    lightVars: {
      '--background': '#ffffff',
      '--foreground': '#0f1419',
      '--card': '#f7f8f8',
      '--card-foreground': '#0f1419',
      '--popover': '#ffffff',
      '--popover-foreground': '#0f1419',
      '--primary': '#1e9df1',
      '--primary-foreground': '#ffffff',
      '--secondary': '#0f1419',
      '--secondary-foreground': '#ffffff',
      '--muted': '#E5E5E6',
      '--muted-foreground': '#0f1419',
      '--accent': '#E3ECF6',
      '--accent-foreground': '#1e9df1',
      '--destructive': '#f4212e',
      '--border': '#e1eaef',
      '--input': '#f7f9fa',
      '--ring': '#1da1f2',
    },
  },
  {
    id: 'mocha-mousse',
    name: 'Mocha Mousse',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#2d2521',
      '--foreground': '#F1F0E5',
      '--card': '#3c332e',
      '--card-foreground': '#F1F0E5',
      '--popover': '#3c332e',
      '--popover-foreground': '#F1F0E5',
      '--primary': '#C39E88',
      '--primary-foreground': '#2d2521',
      '--secondary': '#8A655A',
      '--secondary-foreground': '#F1F0E5',
      '--muted': '#56453F',
      '--muted-foreground': '#c5aa9b',
      '--accent': '#BAAB92',
      '--accent-foreground': '#2d2521',
      '--destructive': '#E57373',
      '--border': '#56453F',
      '--input': '#56453F',
      '--ring': '#C39E88',
    },
    lightVars: {
      '--background': '#F1F0E5',
      '--foreground': '#56453F',
      '--card': '#F1F0E5',
      '--card-foreground': '#56453F',
      '--popover': '#FFFFFF',
      '--popover-foreground': '#56453F',
      '--primary': '#A37764',
      '--primary-foreground': '#FFFFFF',
      '--secondary': '#BAAB92',
      '--secondary-foreground': '#ffffff',
      '--muted': '#E4C7B8',
      '--muted-foreground': '#8A655A',
      '--accent': '#E4C7B8',
      '--accent-foreground': '#56453F',
      '--destructive': '#1f1a17',
      '--border': '#BAAB92',
      '--input': '#BAAB92',
      '--ring': '#A37764',
    },
  },
  {
    id: 'bubblegum',
    name: 'Bubblegum',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "Lora, serif",
    fontBody: "Poppins, sans-serif",
    vars: {
      '--background': '#12242e',
      '--foreground': '#f3e3ea',
      '--card': '#1c2e38',
      '--card-foreground': '#f3e3ea',
      '--popover': '#1c2e38',
      '--popover-foreground': '#f3e3ea',
      '--primary': '#fbe2a7',
      '--primary-foreground': '#12242e',
      '--secondary': '#e4a2b1',
      '--secondary-foreground': '#12242e',
      '--muted': '#24272b',
      '--muted-foreground': '#e4a2b1',
      '--accent': '#c67b96',
      '--accent-foreground': '#f3e3ea',
      '--destructive': '#e35ea4',
      '--border': '#324859',
      '--input': '#20333d',
      '--ring': '#50afb6',
    },
    lightVars: {
      '--background': '#f6e6ee',
      '--foreground': '#5b5b5b',
      '--card': '#fdedc9',
      '--card-foreground': '#5b5b5b',
      '--popover': '#ffffff',
      '--popover-foreground': '#5b5b5b',
      '--primary': '#d04f99',
      '--primary-foreground': '#ffffff',
      '--secondary': '#8acfd1',
      '--secondary-foreground': '#333333',
      '--muted': '#b2e1eb',
      '--muted-foreground': '#7a7a7a',
      '--accent': '#fbe2a7',
      '--accent-foreground': '#333333',
      '--destructive': '#f96f70',
      '--border': '#d04f99',
      '--input': '#e4e4e4',
      '--ring': '#e670ab',
    },
  },
  {
    id: 'amethyst-haze',
    name: 'Amethyst Haze',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#1a1823',
      '--foreground': '#e0ddef',
      '--card': '#232030',
      '--card-foreground': '#e0ddef',
      '--popover': '#232030',
      '--popover-foreground': '#e0ddef',
      '--primary': '#a995c9',
      '--primary-foreground': '#1a1823',
      '--secondary': '#5a5370',
      '--secondary-foreground': '#e0ddef',
      '--muted': '#242031',
      '--muted-foreground': '#a09aad',
      '--accent': '#372e3f',
      '--accent-foreground': '#f2b8c6',
      '--destructive': '#e57373',
      '--border': '#302c40',
      '--input': '#2a273a',
      '--ring': '#a995c9',
    },
    lightVars: {
      '--background': '#f8f7fa',
      '--foreground': '#3d3c4f',
      '--card': '#ffffff',
      '--card-foreground': '#3d3c4f',
      '--popover': '#ffffff',
      '--popover-foreground': '#3d3c4f',
      '--primary': '#8a79ab',
      '--primary-foreground': '#f8f7fa',
      '--secondary': '#dfd9ec',
      '--secondary-foreground': '#3d3c4f',
      '--muted': '#dcd9e3',
      '--muted-foreground': '#6b6880',
      '--accent': '#e6a5b8',
      '--accent-foreground': '#4b2e36',
      '--destructive': '#d95c5c',
      '--border': '#cec9d9',
      '--input': '#eae7f0',
      '--ring': '#8a79ab',
    },
  },
  {
    id: 'notebook',
    name: 'Notebook',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "Georgia, serif",
    fontBody: "Architects Daughter, sans-serif",
    vars: {
      '--background': '#2b2b2b',
      '--foreground': '#dcdcdc',
      '--card': '#333333',
      '--card-foreground': '#dcdcdc',
      '--popover': '#333333',
      '--popover-foreground': '#dcdcdc',
      '--primary': '#b0b0b0',
      '--primary-foreground': '#2b2b2b',
      '--secondary': '#5a5a5a',
      '--secondary-foreground': '#c0c0c0',
      '--muted': '#454545',
      '--muted-foreground': '#a0a0a0',
      '--accent': '#e0e0e0',
      '--accent-foreground': '#333333',
      '--destructive': '#d9afaf',
      '--border': '#4f4f4f',
      '--input': '#333333',
      '--ring': '#c0c0c0',
    },
    lightVars: {
      '--background': '#f9f9f9',
      '--foreground': '#3a3a3a',
      '--card': '#ffffff',
      '--card-foreground': '#3a3a3a',
      '--popover': '#ffffff',
      '--popover-foreground': '#3a3a3a',
      '--primary': '#606060',
      '--primary-foreground': '#f0f0f0',
      '--secondary': '#dedede',
      '--secondary-foreground': '#3a3a3a',
      '--muted': '#e3e3e3',
      '--muted-foreground': '#505050',
      '--accent': '#f3eac8',
      '--accent-foreground': '#5d4037',
      '--destructive': '#c87a7a',
      '--border': '#747272',
      '--input': '#ffffff',
      '--ring': '#a0a0a0',
    },
  },
  {
    id: 'doom-64',
    name: 'Doom 64',
    colorScheme: 'dark',
    radius: '0px',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#1a1a1a',
      '--foreground': '#e0e0e0',
      '--card': '#2a2a2a',
      '--card-foreground': '#e0e0e0',
      '--popover': '#2a2a2a',
      '--popover-foreground': '#e0e0e0',
      '--primary': '#e53935',
      '--primary-foreground': '#ffffff',
      '--secondary': '#689f38',
      '--secondary-foreground': '#000000',
      '--muted': '#252525',
      '--muted-foreground': '#a0a0a0',
      '--accent': '#64b5f6',
      '--accent-foreground': '#000000',
      '--destructive': '#ffa000',
      '--border': '#4a4a4a',
      '--input': '#4a4a4a',
      '--ring': '#e53935',
    },
    lightVars: {
      '--background': '#cccccc',
      '--foreground': '#1f1f1f',
      '--card': '#b0b0b0',
      '--card-foreground': '#1f1f1f',
      '--popover': '#b0b0b0',
      '--popover-foreground': '#1f1f1f',
      '--primary': '#b71c1c',
      '--primary-foreground': '#ffffff',
      '--secondary': '#556b2f',
      '--secondary-foreground': '#ffffff',
      '--muted': '#b8b8b8',
      '--muted-foreground': '#4a4a4a',
      '--accent': '#4682b4',
      '--accent-foreground': '#ffffff',
      '--destructive': '#ff6f00',
      '--border': '#505050',
      '--input': '#505050',
      '--ring': '#b71c1c',
    },
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#181825',
      '--foreground': '#cdd6f4',
      '--card': '#1e1e2e',
      '--card-foreground': '#cdd6f4',
      '--popover': '#45475a',
      '--popover-foreground': '#cdd6f4',
      '--primary': '#cba6f7',
      '--primary-foreground': '#1e1e2e',
      '--secondary': '#585b70',
      '--secondary-foreground': '#cdd6f4',
      '--muted': '#292c3c',
      '--muted-foreground': '#a6adc8',
      '--accent': '#89dceb',
      '--accent-foreground': '#1e1e2e',
      '--destructive': '#f38ba8',
      '--border': '#313244',
      '--input': '#313244',
      '--ring': '#cba6f7',
    },
    lightVars: {
      '--background': '#eff1f5',
      '--foreground': '#4c4f69',
      '--card': '#ffffff',
      '--card-foreground': '#4c4f69',
      '--popover': '#ccd0da',
      '--popover-foreground': '#4c4f69',
      '--primary': '#8839ef',
      '--primary-foreground': '#ffffff',
      '--secondary': '#ccd0da',
      '--secondary-foreground': '#4c4f69',
      '--muted': '#dce0e8',
      '--muted-foreground': '#6c6f85',
      '--accent': '#04a5e5',
      '--accent-foreground': '#ffffff',
      '--destructive': '#d20f39',
      '--border': '#bcc0cc',
      '--input': '#ccd0da',
      '--ring': '#8839ef',
    },
  },
  {
    id: 'graphite',
    name: 'Graphite',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "Georgia, serif",
    fontBody: "Inter, sans-serif",
    vars: {
      '--background': '#1a1a1a',
      '--foreground': '#d9d9d9',
      '--card': '#202020',
      '--card-foreground': '#d9d9d9',
      '--popover': '#202020',
      '--popover-foreground': '#d9d9d9',
      '--primary': '#a0a0a0',
      '--primary-foreground': '#1a1a1a',
      '--secondary': '#303030',
      '--secondary-foreground': '#d9d9d9',
      '--muted': '#2a2a2a',
      '--muted-foreground': '#808080',
      '--accent': '#404040',
      '--accent-foreground': '#d9d9d9',
      '--destructive': '#e06666',
      '--border': '#353535',
      '--input': '#303030',
      '--ring': '#a0a0a0',
    },
    lightVars: {
      '--background': '#f0f0f0',
      '--foreground': '#333333',
      '--card': '#f5f5f5',
      '--card-foreground': '#333333',
      '--popover': '#f5f5f5',
      '--popover-foreground': '#333333',
      '--primary': '#606060',
      '--primary-foreground': '#ffffff',
      '--secondary': '#e0e0e0',
      '--secondary-foreground': '#333333',
      '--muted': '#d9d9d9',
      '--muted-foreground': '#666666',
      '--accent': '#c0c0c0',
      '--accent-foreground': '#333333',
      '--destructive': '#cc3333',
      '--border': '#d0d0d0',
      '--input': '#e0e0e0',
      '--ring': '#606060',
    },
  },
  {
    id: 'perpetuity',
    name: 'Perpetuity',
    colorScheme: 'dark',
    radius: '0.125rem',
    fontDisplay: "Source Code Pro, monospace",
    fontBody: "Source Code Pro, monospace",
    vars: {
      '--background': '#0a1a20',
      '--foreground': '#4de8e8',
      '--card': '#0c2025',
      '--card-foreground': '#4de8e8',
      '--popover': '#0c2025',
      '--popover-foreground': '#4de8e8',
      '--primary': '#4de8e8',
      '--primary-foreground': '#0a1a20',
      '--secondary': '#164955',
      '--secondary-foreground': '#4de8e8',
      '--muted': '#0f3039',
      '--muted-foreground': '#36a5a5',
      '--accent': '#164955',
      '--accent-foreground': '#4de8e8',
      '--destructive': '#e83c3c',
      '--border': '#164955',
      '--input': '#164955',
      '--ring': '#4de8e8',
    },
    lightVars: {
      '--background': '#e8f0f0',
      '--foreground': '#0a4a55',
      '--card': '#f2f7f7',
      '--card-foreground': '#0a4a55',
      '--popover': '#f2f7f7',
      '--popover-foreground': '#0a4a55',
      '--primary': '#06858e',
      '--primary-foreground': '#ffffff',
      '--secondary': '#d9eaea',
      '--secondary-foreground': '#0a4a55',
      '--muted': '#e0eaea',
      '--muted-foreground': '#427a7e',
      '--accent': '#c9e5e7',
      '--accent-foreground': '#0a4a55',
      '--destructive': '#d13838',
      '--border': '#cde0e2',
      '--input': '#d9eaea',
      '--ring': '#06858e',
    },
  },
  {
    id: 'kodama-grove',
    name: 'Kodama Grove',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#3a3529',
      '--foreground': '#ede4d4',
      '--card': '#413c33',
      '--card-foreground': '#ede4d4',
      '--popover': '#413c33',
      '--popover-foreground': '#ede4d4',
      '--primary': '#8a9f7b',
      '--primary-foreground': '#2a2521',
      '--secondary': '#5a5345',
      '--secondary-foreground': '#ede4d4',
      '--muted': '#4a4439',
      '--muted-foreground': '#a8a096',
      '--accent': '#a18f5c',
      '--accent-foreground': '#2a2521',
      '--destructive': '#b5766a',
      '--border': '#5a5345',
      '--input': '#5a5345',
      '--ring': '#8a9f7b',
    },
    lightVars: {
      '--background': '#e4d7b0',
      '--foreground': '#5c4b3e',
      '--card': '#e7dbbf',
      '--card-foreground': '#5c4b3e',
      '--popover': '#f3ead2',
      '--popover-foreground': '#5c4b3e',
      '--primary': '#8d9d4f',
      '--primary-foreground': '#fdfbf6',
      '--secondary': '#decea0',
      '--secondary-foreground': '#5c4b3e',
      '--muted': '#decea0',
      '--muted-foreground': '#85766a',
      '--accent': '#dbc894',
      '--accent-foreground': '#5c4b3e',
      '--destructive': '#d98b7e',
      '--border': '#b19681',
      '--input': '#dbc894',
      '--ring': '#9db18c',
    },
  },
  {
    id: 'cosmic-night',
    name: 'Cosmic Night',
    colorScheme: 'dark',
    radius: '0.5rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#0f0f1a',
      '--foreground': '#e2e2f5',
      '--card': '#1a1a2e',
      '--card-foreground': '#e2e2f5',
      '--popover': '#1a1a2e',
      '--popover-foreground': '#e2e2f5',
      '--primary': '#a48fff',
      '--primary-foreground': '#0f0f1a',
      '--secondary': '#2d2b55',
      '--secondary-foreground': '#c4c2ff',
      '--muted': '#222244',
      '--muted-foreground': '#a0a0c0',
      '--accent': '#303060',
      '--accent-foreground': '#e2e2f5',
      '--destructive': '#ff5470',
      '--border': '#303052',
      '--input': '#303052',
      '--ring': '#a48fff',
    },
    lightVars: {
      '--background': '#f5f5ff',
      '--foreground': '#2a2a4a',
      '--card': '#ffffff',
      '--card-foreground': '#2a2a4a',
      '--popover': '#ffffff',
      '--popover-foreground': '#2a2a4a',
      '--primary': '#6e56cf',
      '--primary-foreground': '#ffffff',
      '--secondary': '#e4dfff',
      '--secondary-foreground': '#4a4080',
      '--muted': '#f0f0fa',
      '--muted-foreground': '#6c6c8a',
      '--accent': '#d8e6ff',
      '--accent-foreground': '#2a2a4a',
      '--destructive': '#ff5470',
      '--border': '#e0e0f0',
      '--input': '#e0e0f0',
      '--ring': '#6e56cf',
    },
  },
  {
    id: 'tangerine',
    name: 'Tangerine',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#1c2433',
      '--foreground': '#e5e5e5',
      '--card': '#2a3040',
      '--card-foreground': '#e5e5e5',
      '--popover': '#262b38',
      '--popover-foreground': '#e5e5e5',
      '--primary': '#e05d38',
      '--primary-foreground': '#ffffff',
      '--secondary': '#2a303e',
      '--secondary-foreground': '#e5e5e5',
      '--muted': '#2a303e',
      '--muted-foreground': '#a3a3a3',
      '--accent': '#2a3656',
      '--accent-foreground': '#bfdbfe',
      '--destructive': '#ef4444',
      '--border': '#3d4354',
      '--input': '#3d4354',
      '--ring': '#e05d38',
    },
    lightVars: {
      '--background': '#e8ebed',
      '--foreground': '#333333',
      '--card': '#ffffff',
      '--card-foreground': '#333333',
      '--popover': '#ffffff',
      '--popover-foreground': '#333333',
      '--primary': '#e05d38',
      '--primary-foreground': '#ffffff',
      '--secondary': '#f3f4f6',
      '--secondary-foreground': '#4b5563',
      '--muted': '#f9fafb',
      '--muted-foreground': '#6b7280',
      '--accent': '#d6e4f0',
      '--accent-foreground': '#1e3a8a',
      '--destructive': '#ef4444',
      '--border': '#dcdfe2',
      '--input': '#f4f5f7',
      '--ring': '#e05d38',
    },
  },
  {
    id: 'quantum-rose',
    name: 'Quantum Rose',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "Playfair Display, serif",
    fontBody: "Quicksand, sans-serif",
    vars: {
      '--background': '#1a0922',
      '--foreground': '#ffb3ff',
      '--card': '#2a1435',
      '--card-foreground': '#ffb3ff',
      '--popover': '#2a1435',
      '--popover-foreground': '#ffb3ff',
      '--primary': '#ff6bef',
      '--primary-foreground': '#180518',
      '--secondary': '#46204f',
      '--secondary-foreground': '#ffb3ff',
      '--muted': '#331941',
      '--muted-foreground': '#d67ad6',
      '--accent': '#5a1f5d',
      '--accent-foreground': '#ffb3ff',
      '--destructive': '#ff2876',
      '--border': '#4a1b5f',
      '--input': '#46204f',
      '--ring': '#ff6bef',
    },
    lightVars: {
      '--background': '#fff0f8',
      '--foreground': '#91185c',
      '--card': '#fff7fc',
      '--card-foreground': '#91185c',
      '--popover': '#fff7fc',
      '--popover-foreground': '#91185c',
      '--primary': '#e6067a',
      '--primary-foreground': '#ffffff',
      '--secondary': '#ffd6ff',
      '--secondary-foreground': '#91185c',
      '--muted': '#ffe3f2',
      '--muted-foreground': '#c04283',
      '--accent': '#ffc1e3',
      '--accent-foreground': '#91185c',
      '--destructive': '#d13869',
      '--border': '#ffc7e6',
      '--input': '#ffd6ff',
      '--ring': '#e6067a',
    },
  },
  {
    id: 'nature',
    name: 'Nature',
    colorScheme: 'dark',
    radius: '0.5rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#1c2a1f',
      '--foreground': '#f0ebe5',
      '--card': '#2d3a2e',
      '--card-foreground': '#f0ebe5',
      '--popover': '#2d3a2e',
      '--popover-foreground': '#f0ebe5',
      '--primary': '#4caf50',
      '--primary-foreground': '#0a1f0c',
      '--secondary': '#3e4a3d',
      '--secondary-foreground': '#d7e0d6',
      '--muted': '#252f26',
      '--muted-foreground': '#d7cfc4',
      '--accent': '#388e3c',
      '--accent-foreground': '#f0ebe5',
      '--destructive': '#c62828',
      '--border': '#3e4a3d',
      '--input': '#3e4a3d',
      '--ring': '#4caf50',
    },
    lightVars: {
      '--background': '#f8f5f0',
      '--foreground': '#3e2723',
      '--card': '#f8f5f0',
      '--card-foreground': '#3e2723',
      '--popover': '#f8f5f0',
      '--popover-foreground': '#3e2723',
      '--primary': '#2e7d32',
      '--primary-foreground': '#ffffff',
      '--secondary': '#e8f5e9',
      '--secondary-foreground': '#1b5e20',
      '--muted': '#f0e9e0',
      '--muted-foreground': '#6d4c41',
      '--accent': '#c8e6c9',
      '--accent-foreground': '#1b5e20',
      '--destructive': '#c62828',
      '--border': '#e0d6c9',
      '--input': '#e0d6c9',
      '--ring': '#2e7d32',
    },
  },
  {
    id: 'bold-tech',
    name: 'Bold Tech',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#0f172a',
      '--foreground': '#e0e7ff',
      '--card': '#1e1b4b',
      '--card-foreground': '#e0e7ff',
      '--popover': '#1e1b4b',
      '--popover-foreground': '#e0e7ff',
      '--primary': '#8b5cf6',
      '--primary-foreground': '#ffffff',
      '--secondary': '#1e1b4b',
      '--secondary-foreground': '#e0e7ff',
      '--muted': '#171447',
      '--muted-foreground': '#c4b5fd',
      '--accent': '#4338ca',
      '--accent-foreground': '#e0e7ff',
      '--destructive': '#ef4444',
      '--border': '#2e1065',
      '--input': '#2e1065',
      '--ring': '#8b5cf6',
    },
    lightVars: {
      '--background': '#ffffff',
      '--foreground': '#312e81',
      '--card': '#ffffff',
      '--card-foreground': '#312e81',
      '--popover': '#ffffff',
      '--popover-foreground': '#312e81',
      '--primary': '#8b5cf6',
      '--primary-foreground': '#ffffff',
      '--secondary': '#f3f0ff',
      '--secondary-foreground': '#4338ca',
      '--muted': '#f5f3ff',
      '--muted-foreground': '#7c3aed',
      '--accent': '#dbeafe',
      '--accent-foreground': '#1e40af',
      '--destructive': '#ef4444',
      '--border': '#e0e7ff',
      '--input': '#e0e7ff',
      '--ring': '#8b5cf6',
    },
  },
  {
    id: 'elegant-luxury',
    name: 'Elegant Luxury',
    colorScheme: 'dark',
    radius: '0.375rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#1c1917',
      '--foreground': '#f5f5f4',
      '--card': '#292524',
      '--card-foreground': '#f5f5f4',
      '--popover': '#292524',
      '--popover-foreground': '#f5f5f4',
      '--primary': '#b91c1c',
      '--primary-foreground': '#faf7f5',
      '--secondary': '#92400e',
      '--secondary-foreground': '#fef3c7',
      '--muted': '#1f1c1a',
      '--muted-foreground': '#d6d3d1',
      '--accent': '#b45309',
      '--accent-foreground': '#fef3c7',
      '--destructive': '#ef4444',
      '--border': '#44403c',
      '--input': '#44403c',
      '--ring': '#b91c1c',
    },
    lightVars: {
      '--background': '#faf7f5',
      '--foreground': '#1a1a1a',
      '--card': '#faf7f5',
      '--card-foreground': '#1a1a1a',
      '--popover': '#faf7f5',
      '--popover-foreground': '#1a1a1a',
      '--primary': '#9b2c2c',
      '--primary-foreground': '#ffffff',
      '--secondary': '#fdf2d6',
      '--secondary-foreground': '#805500',
      '--muted': '#f0ebe8',
      '--muted-foreground': '#57534e',
      '--accent': '#fef3c7',
      '--accent-foreground': '#7f1d1d',
      '--destructive': '#991b1b',
      '--border': '#f5e8d2',
      '--input': '#f5e8d2',
      '--ring': '#9b2c2c',
    },
  },
  {
    id: 'amber-minimal',
    name: 'Amber Minimal',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#171717',
      '--foreground': '#e5e5e5',
      '--card': '#262626',
      '--card-foreground': '#e5e5e5',
      '--popover': '#262626',
      '--popover-foreground': '#e5e5e5',
      '--primary': '#f59e0b',
      '--primary-foreground': '#000000',
      '--secondary': '#262626',
      '--secondary-foreground': '#e5e5e5',
      '--muted': '#1f1f1f',
      '--muted-foreground': '#a3a3a3',
      '--accent': '#92400e',
      '--accent-foreground': '#fde68a',
      '--destructive': '#ef4444',
      '--border': '#404040',
      '--input': '#404040',
      '--ring': '#f59e0b',
    },
    lightVars: {
      '--background': '#ffffff',
      '--foreground': '#262626',
      '--card': '#ffffff',
      '--card-foreground': '#262626',
      '--popover': '#ffffff',
      '--popover-foreground': '#262626',
      '--primary': '#f59e0b',
      '--primary-foreground': '#000000',
      '--secondary': '#f3f4f6',
      '--secondary-foreground': '#4b5563',
      '--muted': '#f9fafb',
      '--muted-foreground': '#6b7280',
      '--accent': '#fffbeb',
      '--accent-foreground': '#92400e',
      '--destructive': '#ef4444',
      '--border': '#e5e7eb',
      '--input': '#e5e7eb',
      '--ring': '#f59e0b',
    },
  },
  {
    id: 'supabase',
    name: 'Supabase',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#121212',
      '--foreground': '#e2e8f0',
      '--card': '#171717',
      '--card-foreground': '#e2e8f0',
      '--popover': '#242424',
      '--popover-foreground': '#a9a9a9',
      '--primary': '#006239',
      '--primary-foreground': '#dde8e3',
      '--secondary': '#242424',
      '--secondary-foreground': '#fafafa',
      '--muted': '#1f1f1f',
      '--muted-foreground': '#a2a2a2',
      '--accent': '#313131',
      '--accent-foreground': '#fafafa',
      '--destructive': '#541c15',
      '--border': '#292929',
      '--input': '#242424',
      '--ring': '#4ade80',
    },
    lightVars: {
      '--background': '#fcfcfc',
      '--foreground': '#171717',
      '--card': '#fcfcfc',
      '--card-foreground': '#171717',
      '--popover': '#fcfcfc',
      '--popover-foreground': '#525252',
      '--primary': '#72e3ad',
      '--primary-foreground': '#1e2723',
      '--secondary': '#fdfdfd',
      '--secondary-foreground': '#171717',
      '--muted': '#ededed',
      '--muted-foreground': '#202020',
      '--accent': '#ededed',
      '--accent-foreground': '#202020',
      '--destructive': '#ca3214',
      '--border': '#dfdfdf',
      '--input': '#f6f6f6',
      '--ring': '#72e3ad',
    },
  },
  {
    id: 'neo-brutalism',
    name: 'Neo Brutalism',
    colorScheme: 'dark',
    radius: '0px',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#000000',
      '--foreground': '#ffffff',
      '--card': '#333333',
      '--card-foreground': '#ffffff',
      '--popover': '#333333',
      '--popover-foreground': '#ffffff',
      '--primary': '#ff6666',
      '--primary-foreground': '#000000',
      '--secondary': '#ffff33',
      '--secondary-foreground': '#000000',
      '--muted': '#1a1a1a',
      '--muted-foreground': '#cccccc',
      '--accent': '#3399ff',
      '--accent-foreground': '#000000',
      '--destructive': '#ffffff',
      '--border': '#ffffff',
      '--input': '#ffffff',
      '--ring': '#ff6666',
    },
    lightVars: {
      '--background': '#ffffff',
      '--foreground': '#000000',
      '--card': '#ffffff',
      '--card-foreground': '#000000',
      '--popover': '#ffffff',
      '--popover-foreground': '#000000',
      '--primary': '#ff3333',
      '--primary-foreground': '#ffffff',
      '--secondary': '#ffff00',
      '--secondary-foreground': '#000000',
      '--muted': '#f0f0f0',
      '--muted-foreground': '#333333',
      '--accent': '#0066ff',
      '--accent-foreground': '#ffffff',
      '--destructive': '#000000',
      '--border': '#000000',
      '--input': '#000000',
      '--ring': '#ff3333',
    },
  },
  {
    id: 'solar-dusk',
    name: 'Solar Dusk',
    colorScheme: 'dark',
    radius: '0.3rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#1C1917',
      '--foreground': '#F5F5F4',
      '--card': '#292524',
      '--card-foreground': '#F5F5F4',
      '--popover': '#292524',
      '--popover-foreground': '#F5F5F4',
      '--primary': '#F97316',
      '--primary-foreground': '#FFFFFF',
      '--secondary': '#57534E',
      '--secondary-foreground': '#E7E5E4',
      '--muted': '#201d1a',
      '--muted-foreground': '#A8A29E',
      '--accent': '#1e4252',
      '--accent-foreground': '#E7E5E4',
      '--destructive': '#DC2626',
      '--border': '#44403C',
      '--input': '#44403C',
      '--ring': '#F97316',
    },
    lightVars: {
      '--background': '#FDFBF7',
      '--foreground': '#4A3B33',
      '--card': '#F8F4EE',
      '--card-foreground': '#4A3B33',
      '--popover': '#F8F4EE',
      '--popover-foreground': '#4A3B33',
      '--primary': '#B45309',
      '--primary-foreground': '#FFFFFF',
      '--secondary': '#E4C090',
      '--secondary-foreground': '#57534E',
      '--muted': '#F1E9DA',
      '--muted-foreground': '#78716C',
      '--accent': '#f2daba',
      '--accent-foreground': '#57534E',
      '--destructive': '#991B1B',
      '--border': '#E4D9BC',
      '--input': '#E4D9BC',
      '--ring': '#B45309',
    },
  },
  {
    id: 'claymorphism',
    name: 'Claymorphism',
    colorScheme: 'dark',
    radius: '1.25rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#1e1b18',
      '--foreground': '#e2e8f0',
      '--card': '#2c2825',
      '--card-foreground': '#e2e8f0',
      '--popover': '#2c2825',
      '--popover-foreground': '#e2e8f0',
      '--primary': '#818cf8',
      '--primary-foreground': '#1e1b18',
      '--secondary': '#3a3633',
      '--secondary-foreground': '#d1d5db',
      '--muted': '#1f1c19',
      '--muted-foreground': '#9ca3af',
      '--accent': '#484441',
      '--accent-foreground': '#d1d5db',
      '--destructive': '#ef4444',
      '--border': '#3a3633',
      '--input': '#3a3633',
      '--ring': '#818cf8',
    },
    lightVars: {
      '--background': '#e7e5e4',
      '--foreground': '#1e293b',
      '--card': '#f5f5f4',
      '--card-foreground': '#1e293b',
      '--popover': '#f5f5f4',
      '--popover-foreground': '#1e293b',
      '--primary': '#6366f1',
      '--primary-foreground': '#ffffff',
      '--secondary': '#d6d3d1',
      '--secondary-foreground': '#4b5563',
      '--muted': '#e7e5e4',
      '--muted-foreground': '#6b7280',
      '--accent': '#f3e5f5',
      '--accent-foreground': '#374151',
      '--destructive': '#ef4444',
      '--border': '#d6d3d1',
      '--input': '#d6d3d1',
      '--ring': '#6366f1',
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    colorScheme: 'dark',
    radius: '0.5rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#0c0c1d',
      '--foreground': '#eceff4',
      '--card': '#1e1e3f',
      '--card-foreground': '#eceff4',
      '--popover': '#1e1e3f',
      '--popover-foreground': '#eceff4',
      '--primary': '#ff00c8',
      '--primary-foreground': '#ffffff',
      '--secondary': '#1e1e3f',
      '--secondary-foreground': '#eceff4',
      '--muted': '#151530',
      '--muted-foreground': '#8085a6',
      '--accent': '#00ffcc',
      '--accent-foreground': '#0c0c1d',
      '--destructive': '#ff3d00',
      '--border': '#2e2e5e',
      '--input': '#2e2e5e',
      '--ring': '#ff00c8',
    },
    lightVars: {
      '--background': '#f8f9fa',
      '--foreground': '#0c0c1d',
      '--card': '#ffffff',
      '--card-foreground': '#0c0c1d',
      '--popover': '#ffffff',
      '--popover-foreground': '#0c0c1d',
      '--primary': '#ff00c8',
      '--primary-foreground': '#ffffff',
      '--secondary': '#f0f0ff',
      '--secondary-foreground': '#0c0c1d',
      '--muted': '#f0f0ff',
      '--muted-foreground': '#0c0c1d',
      '--accent': '#00ffcc',
      '--accent-foreground': '#0c0c1d',
      '--destructive': '#ff3d00',
      '--border': '#dfe6e9',
      '--input': '#dfe6e9',
      '--ring': '#ff00c8',
    },
  },
  {
    id: 'pastel-dreams',
    name: 'Pastel Dreams',
    colorScheme: 'dark',
    radius: '1.5rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#1c1917',
      '--foreground': '#e0e7ff',
      '--card': '#2d2535',
      '--card-foreground': '#e0e7ff',
      '--popover': '#2d2535',
      '--popover-foreground': '#e0e7ff',
      '--primary': '#c0aafd',
      '--primary-foreground': '#1c1917',
      '--secondary': '#3f324a',
      '--secondary-foreground': '#d1d5db',
      '--muted': '#20182b',
      '--muted-foreground': '#9ca3af',
      '--accent': '#4a3d5a',
      '--accent-foreground': '#d1d5db',
      '--destructive': '#fca5a5',
      '--border': '#3f324a',
      '--input': '#3f324a',
      '--ring': '#c0aafd',
    },
    lightVars: {
      '--background': '#f7f3f9',
      '--foreground': '#374151',
      '--card': '#ffffff',
      '--card-foreground': '#374151',
      '--popover': '#ffffff',
      '--popover-foreground': '#374151',
      '--primary': '#a78bfa',
      '--primary-foreground': '#ffffff',
      '--secondary': '#e9d8fd',
      '--secondary-foreground': '#4b5563',
      '--muted': '#f3e8ff',
      '--muted-foreground': '#6b7280',
      '--accent': '#f3e5f5',
      '--accent-foreground': '#374151',
      '--destructive': '#fca5a5',
      '--border': '#e9d8fd',
      '--input': '#e9d8fd',
      '--ring': '#a78bfa',
    },
  },
  {
    id: 'clean-slate',
    name: 'Clean Slate',
    colorScheme: 'dark',
    radius: '0.5rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#0f172a',
      '--foreground': '#e2e8f0',
      '--card': '#1e293b',
      '--card-foreground': '#e2e8f0',
      '--popover': '#1e293b',
      '--popover-foreground': '#e2e8f0',
      '--primary': '#818cf8',
      '--primary-foreground': '#0f172a',
      '--secondary': '#2d3748',
      '--secondary-foreground': '#d1d5db',
      '--muted': '#152032',
      '--muted-foreground': '#9ca3af',
      '--accent': '#374151',
      '--accent-foreground': '#d1d5db',
      '--destructive': '#ef4444',
      '--border': '#4b5563',
      '--input': '#4b5563',
      '--ring': '#818cf8',
    },
    lightVars: {
      '--background': '#f8fafc',
      '--foreground': '#1e293b',
      '--card': '#ffffff',
      '--card-foreground': '#1e293b',
      '--popover': '#ffffff',
      '--popover-foreground': '#1e293b',
      '--primary': '#6366f1',
      '--primary-foreground': '#ffffff',
      '--secondary': '#e5e7eb',
      '--secondary-foreground': '#374151',
      '--muted': '#f3f4f6',
      '--muted-foreground': '#6b7280',
      '--accent': '#e0e7ff',
      '--accent-foreground': '#374151',
      '--destructive': '#ef4444',
      '--border': '#d1d5db',
      '--input': '#d1d5db',
      '--ring': '#6366f1',
    },
  },
  {
    id: 'caffeine',
    name: 'Caffeine',
    colorScheme: 'dark',
    radius: '0.5rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#111111',
      '--foreground': '#eeeeee',
      '--card': '#191919',
      '--card-foreground': '#eeeeee',
      '--popover': '#191919',
      '--popover-foreground': '#eeeeee',
      '--primary': '#ffe0c2',
      '--primary-foreground': '#081a1b',
      '--secondary': '#393028',
      '--secondary-foreground': '#ffe0c2',
      '--muted': '#222222',
      '--muted-foreground': '#b4b4b4',
      '--accent': '#2a2a2a',
      '--accent-foreground': '#eeeeee',
      '--destructive': '#e54d2e',
      '--border': '#201e18',
      '--input': '#484848',
      '--ring': '#ffe0c2',
    },
    lightVars: {
      '--background': '#f9f9f9',
      '--foreground': '#202020',
      '--card': '#fcfcfc',
      '--card-foreground': '#202020',
      '--popover': '#fcfcfc',
      '--popover-foreground': '#202020',
      '--primary': '#644a40',
      '--primary-foreground': '#ffffff',
      '--secondary': '#ffdfb5',
      '--secondary-foreground': '#582d1d',
      '--muted': '#efefef',
      '--muted-foreground': '#646464',
      '--accent': '#e8e8e8',
      '--accent-foreground': '#202020',
      '--destructive': '#e54d2e',
      '--border': '#d8d8d8',
      '--input': '#d8d8d8',
      '--ring': '#644a40',
    },
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    colorScheme: 'dark',
    radius: '0.5rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#0f172a',
      '--foreground': '#d1d5db',
      '--card': '#1e293b',
      '--card-foreground': '#d1d5db',
      '--popover': '#1e293b',
      '--popover-foreground': '#d1d5db',
      '--primary': '#34d399',
      '--primary-foreground': '#0f172a',
      '--secondary': '#2d3748',
      '--secondary-foreground': '#a1a1aa',
      '--muted': '#19212e',
      '--muted-foreground': '#6b7280',
      '--accent': '#374151',
      '--accent-foreground': '#a1a1aa',
      '--destructive': '#ef4444',
      '--border': '#4b5563',
      '--input': '#4b5563',
      '--ring': '#34d399',
    },
    lightVars: {
      '--background': '#f0f8ff',
      '--foreground': '#374151',
      '--card': '#ffffff',
      '--card-foreground': '#374151',
      '--popover': '#ffffff',
      '--popover-foreground': '#374151',
      '--primary': '#22c55e',
      '--primary-foreground': '#ffffff',
      '--secondary': '#e0f2fe',
      '--secondary-foreground': '#4b5563',
      '--muted': '#f3f4f6',
      '--muted-foreground': '#6b7280',
      '--accent': '#d1fae5',
      '--accent-foreground': '#374151',
      '--destructive': '#ef4444',
      '--border': '#e5e7eb',
      '--input': '#e5e7eb',
      '--ring': '#22c55e',
    },
  },
  {
    id: 'retro-arcade',
    name: 'Retro Arcade',
    colorScheme: 'dark',
    radius: '0.25rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#002b36',
      '--foreground': '#93a1a1',
      '--card': '#073642',
      '--card-foreground': '#93a1a1',
      '--popover': '#073642',
      '--popover-foreground': '#93a1a1',
      '--primary': '#d33682',
      '--primary-foreground': '#ffffff',
      '--secondary': '#2aa198',
      '--secondary-foreground': '#ffffff',
      '--muted': '#586e75',
      '--muted-foreground': '#93a1a1',
      '--accent': '#cb4b16',
      '--accent-foreground': '#ffffff',
      '--destructive': '#dc322f',
      '--border': '#586e75',
      '--input': '#586e75',
      '--ring': '#d33682',
    },
    lightVars: {
      '--background': '#fdf6e3',
      '--foreground': '#073642',
      '--card': '#eee8d5',
      '--card-foreground': '#073642',
      '--popover': '#eee8d5',
      '--popover-foreground': '#073642',
      '--primary': '#d33682',
      '--primary-foreground': '#ffffff',
      '--secondary': '#2aa198',
      '--secondary-foreground': '#ffffff',
      '--muted': '#93a1a1',
      '--muted-foreground': '#073642',
      '--accent': '#cb4b16',
      '--accent-foreground': '#ffffff',
      '--destructive': '#dc322f',
      '--border': '#839496',
      '--input': '#839496',
      '--ring': '#d33682',
    },
  },
  {
    id: 'midnight-bloom',
    name: 'Midnight Bloom',
    colorScheme: 'dark',
    radius: '0.5rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#1a1d23',
      '--foreground': '#e5e5e5',
      '--card': '#2f3436',
      '--card-foreground': '#e5e5e5',
      '--popover': '#2f3436',
      '--popover-foreground': '#e5e5e5',
      '--primary': '#6c5ce7',
      '--primary-foreground': '#ffffff',
      '--secondary': '#4b0082',
      '--secondary-foreground': '#e5e5e5',
      '--muted': '#444444',
      '--muted-foreground': '#a3a3a3',
      '--accent': '#6495ed',
      '--accent-foreground': '#e5e5e5',
      '--destructive': '#ef4444',
      '--border': '#444444',
      '--input': '#444444',
      '--ring': '#6c5ce7',
    },
    lightVars: {
      '--background': '#f9f9f9',
      '--foreground': '#333333',
      '--card': '#ffffff',
      '--card-foreground': '#333333',
      '--popover': '#ffffff',
      '--popover-foreground': '#333333',
      '--primary': '#6c5ce7',
      '--primary-foreground': '#ffffff',
      '--secondary': '#a1c9f2',
      '--secondary-foreground': '#333333',
      '--muted': '#c9c4b5',
      '--muted-foreground': '#6e6e6e',
      '--accent': '#8b9467',
      '--accent-foreground': '#ffffff',
      '--destructive': '#ef4444',
      '--border': '#d4d4d4',
      '--input': '#d4d4d4',
      '--ring': '#6c5ce7',
    },
  },
  {
    id: 'candyland',
    name: 'Candyland',
    colorScheme: 'dark',
    radius: '0.5rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#1a1d23',
      '--foreground': '#e5e5e5',
      '--card': '#2f3436',
      '--card-foreground': '#e5e5e5',
      '--popover': '#2f3436',
      '--popover-foreground': '#e5e5e5',
      '--primary': '#ff99cc',
      '--primary-foreground': '#000000',
      '--secondary': '#33cc33',
      '--secondary-foreground': '#000000',
      '--muted': '#444444',
      '--muted-foreground': '#a3a3a3',
      '--accent': '#87ceeb',
      '--accent-foreground': '#000000',
      '--destructive': '#ef4444',
      '--border': '#444444',
      '--input': '#444444',
      '--ring': '#ff99cc',
    },
    lightVars: {
      '--background': '#f7f9fa',
      '--foreground': '#333333',
      '--card': '#ffffff',
      '--card-foreground': '#333333',
      '--popover': '#ffffff',
      '--popover-foreground': '#333333',
      '--primary': '#ffc0cb',
      '--primary-foreground': '#000000',
      '--secondary': '#87ceeb',
      '--secondary-foreground': '#000000',
      '--muted': '#ddd9c4',
      '--muted-foreground': '#6e6e6e',
      '--accent': '#ffff00',
      '--accent-foreground': '#000000',
      '--destructive': '#ef4444',
      '--border': '#d4d4d4',
      '--input': '#d4d4d4',
      '--ring': '#ffc0cb',
    },
  },
  {
    id: 'northern-lights',
    name: 'Northern Lights',
    colorScheme: 'dark',
    radius: '0.5rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#1a1d23',
      '--foreground': '#e5e5e5',
      '--card': '#2f3436',
      '--card-foreground': '#e5e5e5',
      '--popover': '#2f3436',
      '--popover-foreground': '#e5e5e5',
      '--primary': '#34a85a',
      '--primary-foreground': '#ffffff',
      '--secondary': '#4682b4',
      '--secondary-foreground': '#e5e5e5',
      '--muted': '#444444',
      '--muted-foreground': '#a3a3a3',
      '--accent': '#6495ed',
      '--accent-foreground': '#e5e5e5',
      '--destructive': '#ef4444',
      '--border': '#444444',
      '--input': '#444444',
      '--ring': '#34a85a',
    },
    lightVars: {
      '--background': '#f9f9fa',
      '--foreground': '#333333',
      '--card': '#ffffff',
      '--card-foreground': '#333333',
      '--popover': '#ffffff',
      '--popover-foreground': '#333333',
      '--primary': '#34a85a',
      '--primary-foreground': '#ffffff',
      '--secondary': '#6495ed',
      '--secondary-foreground': '#ffffff',
      '--muted': '#ddd9c4',
      '--muted-foreground': '#6e6e6e',
      '--accent': '#66d9ef',
      '--accent-foreground': '#333333',
      '--destructive': '#ef4444',
      '--border': '#d4d4d4',
      '--input': '#d4d4d4',
      '--ring': '#34a85a',
    },
  },
  {
    id: 'vintage-paper',
    name: 'Vintage Paper',
    colorScheme: 'dark',
    radius: '0.25rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#2d2621',
      '--foreground': '#ece5d8',
      '--card': '#3a322c',
      '--card-foreground': '#ece5d8',
      '--popover': '#3a322c',
      '--popover-foreground': '#ece5d8',
      '--primary': '#c0a080',
      '--primary-foreground': '#2d2621',
      '--secondary': '#4a4039',
      '--secondary-foreground': '#ece5d8',
      '--muted': '#312b26',
      '--muted-foreground': '#c5bcac',
      '--accent': '#59493e',
      '--accent-foreground': '#ece5d8',
      '--destructive': '#b54a35',
      '--border': '#4a4039',
      '--input': '#4a4039',
      '--ring': '#c0a080',
    },
    lightVars: {
      '--background': '#f5f1e6',
      '--foreground': '#4a3f35',
      '--card': '#fffcf5',
      '--card-foreground': '#4a3f35',
      '--popover': '#fffcf5',
      '--popover-foreground': '#4a3f35',
      '--primary': '#a67c52',
      '--primary-foreground': '#ffffff',
      '--secondary': '#e2d8c3',
      '--secondary-foreground': '#5c4d3f',
      '--muted': '#ece5d8',
      '--muted-foreground': '#7d6b56',
      '--accent': '#d4c8aa',
      '--accent-foreground': '#4a3f35',
      '--destructive': '#b54a35',
      '--border': '#dbd0ba',
      '--input': '#dbd0ba',
      '--ring': '#a67c52',
    },
  },
  {
    id: 'sunset-horizon',
    name: 'Sunset Horizon',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#2a2024',
      '--foreground': '#f2e9e4',
      '--card': '#392f35',
      '--card-foreground': '#f2e9e4',
      '--popover': '#392f35',
      '--popover-foreground': '#f2e9e4',
      '--primary': '#ff7e5f',
      '--primary-foreground': '#ffffff',
      '--secondary': '#463a41',
      '--secondary-foreground': '#f2e9e4',
      '--muted': '#30272c',
      '--muted-foreground': '#d7c6bc',
      '--accent': '#feb47b',
      '--accent-foreground': '#2a2024',
      '--destructive': '#e63946',
      '--border': '#463a41',
      '--input': '#463a41',
      '--ring': '#ff7e5f',
    },
    lightVars: {
      '--background': '#fff9f5',
      '--foreground': '#3d3436',
      '--card': '#ffffff',
      '--card-foreground': '#3d3436',
      '--popover': '#ffffff',
      '--popover-foreground': '#3d3436',
      '--primary': '#ff7e5f',
      '--primary-foreground': '#ffffff',
      '--secondary': '#ffedea',
      '--secondary-foreground': '#b35340',
      '--muted': '#fff0eb',
      '--muted-foreground': '#78716C',
      '--accent': '#feb47b',
      '--accent-foreground': '#3d3436',
      '--destructive': '#e63946',
      '--border': '#ffe0d6',
      '--input': '#ffe0d6',
      '--ring': '#ff7e5f',
    },
  },
  {
    id: 'starry-night',
    name: 'Starry Night',
    colorScheme: 'dark',
    radius: '0.5rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#181a24',
      '--foreground': '#e6eaf3',
      '--card': '#23243a',
      '--card-foreground': '#e6eaf3',
      '--popover': '#23243a',
      '--popover-foreground': '#ffe066',
      '--primary': '#3a5ba0',
      '--primary-foreground': '#ffe066',
      '--secondary': '#ffe066',
      '--secondary-foreground': '#23243a',
      '--muted': '#1d1e2f',
      '--muted-foreground': '#7a88a1',
      '--accent': '#bccdf0',
      '--accent-foreground': '#181a24',
      '--destructive': '#a04a6c',
      '--border': '#2d2e3e',
      '--input': '#3a5ba0',
      '--ring': '#ffe066',
    },
    lightVars: {
      '--background': '#f5f7fa',
      '--foreground': '#1a2238',
      '--card': '#e3eaf2',
      '--card-foreground': '#1a2238',
      '--popover': '#fffbe6',
      '--popover-foreground': '#1a2238',
      '--primary': '#3a5ba0',
      '--primary-foreground': '#fffbe6',
      '--secondary': '#f7c873',
      '--secondary-foreground': '#1a2238',
      '--muted': '#e5e5df',
      '--muted-foreground': '#3a5ba0',
      '--accent': '#6ea3c1',
      '--accent-foreground': '#fffbe6',
      '--destructive': '#2d1e2f',
      '--border': '#b0b8c1',
      '--input': '#6ea3c1',
      '--ring': '#f7c873',
    },
  },
  {
    id: 'claude',
    name: 'Claude',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#262624',
      '--foreground': '#c3c0b6',
      '--card': '#262624',
      '--card-foreground': '#faf9f5',
      '--popover': '#30302e',
      '--popover-foreground': '#e5e5e2',
      '--primary': '#d97757',
      '--primary-foreground': '#ffffff',
      '--secondary': '#faf9f5',
      '--secondary-foreground': '#30302e',
      '--muted': '#1b1b19',
      '--muted-foreground': '#b7b5a9',
      '--accent': '#1a1915',
      '--accent-foreground': '#f5f4ee',
      '--destructive': '#ef4444',
      '--border': '#3e3e38',
      '--input': '#52514a',
      '--ring': '#d97757',
    },
    lightVars: {
      '--background': '#faf9f5',
      '--foreground': '#3d3929',
      '--card': '#faf9f5',
      '--card-foreground': '#141413',
      '--popover': '#ffffff',
      '--popover-foreground': '#28261b',
      '--primary': '#c96442',
      '--primary-foreground': '#ffffff',
      '--secondary': '#e9e6dc',
      '--secondary-foreground': '#535146',
      '--muted': '#ede9de',
      '--muted-foreground': '#83827d',
      '--accent': '#e9e6dc',
      '--accent-foreground': '#28261b',
      '--destructive': '#141413',
      '--border': '#dad9d4',
      '--input': '#b4b2a7',
      '--ring': '#c96442',
    },
  },
  {
    id: 'vercel',
    name: 'Vercel',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "Georgia, serif",
    fontBody: "Geist, sans-serif",
    vars: {
      '--background': 'oklch(0 0 0)',
      '--foreground': 'oklch(1.00 0 0)',
      '--card': 'oklch(0.14 0 0)',
      '--card-foreground': 'oklch(1.00 0 0)',
      '--popover': 'oklch(0.18 0 0)',
      '--popover-foreground': 'oklch(1.00 0 0)',
      '--primary': 'oklch(1.00 0 0)',
      '--primary-foreground': 'oklch(0 0 0)',
      '--secondary': 'oklch(0.25 0 0)',
      '--secondary-foreground': 'oklch(1.00 0 0)',
      '--muted': 'oklch(0.23 0 0)',
      '--muted-foreground': 'oklch(0.72 0 0)',
      '--accent': 'oklch(0.32 0 0)',
      '--accent-foreground': 'oklch(1.00 0 0)',
      '--destructive': 'oklch(0.69 0.20 23.91)',
      '--border': 'oklch(0.26 0 0)',
      '--input': 'oklch(0.32 0 0)',
      '--ring': 'oklch(0.72 0 0)',
    },
    lightVars: {
      '--background': 'oklch(0.99 0 0)',
      '--foreground': 'oklch(0 0 0)',
      '--card': 'oklch(1.00 0 0)',
      '--card-foreground': 'oklch(0 0 0)',
      '--popover': 'oklch(0.99 0 0)',
      '--popover-foreground': 'oklch(0 0 0)',
      '--primary': 'oklch(0 0 0)',
      '--primary-foreground': 'oklch(1.00 0 0)',
      '--secondary': 'oklch(0.94 0 0)',
      '--secondary-foreground': 'oklch(0 0 0)',
      '--muted': 'oklch(0.97 0 0)',
      '--muted-foreground': 'oklch(0.44 0 0)',
      '--accent': 'oklch(0.94 0 0)',
      '--accent-foreground': 'oklch(0 0 0)',
      '--destructive': 'oklch(0.63 0.19 23.03)',
      '--border': 'oklch(0.92 0 0)',
      '--input': 'oklch(0.94 0 0)',
      '--ring': 'oklch(0 0 0)',
    },
  },
  {
    id: 'darkmatter',
    name: 'Darkmatter',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#121113',
      '--foreground': '#c1c1c1',
      '--card': '#121212',
      '--card-foreground': '#c1c1c1',
      '--popover': '#121113',
      '--popover-foreground': '#c1c1c1',
      '--primary': '#e78a53',
      '--primary-foreground': '#121113',
      '--secondary': '#5f8787',
      '--secondary-foreground': '#121113',
      '--muted': '#222222',
      '--muted-foreground': '#888888',
      '--accent': '#333333',
      '--accent-foreground': '#c1c1c1',
      '--destructive': '#5f8787',
      '--border': '#222222',
      '--input': '#222222',
      '--ring': '#e78a53',
    },
    lightVars: {
      '--background': '#ffffff',
      '--foreground': '#111827',
      '--card': '#ffffff',
      '--card-foreground': '#111827',
      '--popover': '#ffffff',
      '--popover-foreground': '#111827',
      '--primary': '#d87943',
      '--primary-foreground': '#ffffff',
      '--secondary': '#527575',
      '--secondary-foreground': '#ffffff',
      '--muted': '#f3f4f6',
      '--muted-foreground': '#6b7280',
      '--accent': '#eeeeee',
      '--accent-foreground': '#111827',
      '--destructive': '#ef4444',
      '--border': '#e5e7eb',
      '--input': '#e5e7eb',
      '--ring': '#d87943',
    },
  },
  {
    id: 'mono',
    name: 'Mono',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#0a0a0a',
      '--foreground': '#fafafa',
      '--card': '#191919',
      '--card-foreground': '#fafafa',
      '--popover': '#262626',
      '--popover-foreground': '#fafafa',
      '--primary': '#737373',
      '--primary-foreground': '#fafafa',
      '--secondary': '#262626',
      '--secondary-foreground': '#fafafa',
      '--muted': '#262626',
      '--muted-foreground': '#a1a1a1',
      '--accent': '#404040',
      '--accent-foreground': '#fafafa',
      '--destructive': '#ff6467',
      '--border': '#383838',
      '--input': '#525252',
      '--ring': '#737373',
    },
    lightVars: {
      '--background': '#ffffff',
      '--foreground': '#0a0a0a',
      '--card': '#ffffff',
      '--card-foreground': '#0a0a0a',
      '--popover': '#ffffff',
      '--popover-foreground': '#0a0a0a',
      '--primary': '#737373',
      '--primary-foreground': '#fafafa',
      '--secondary': '#f5f5f5',
      '--secondary-foreground': '#171717',
      '--muted': '#f5f5f5',
      '--muted-foreground': '#717171',
      '--accent': '#f5f5f5',
      '--accent-foreground': '#171717',
      '--destructive': '#e7000b',
      '--border': '#e5e5e5',
      '--input': '#e5e5e5',
      '--ring': '#a1a1a1',
    },
  },
  {
    id: 'soft-pop',
    name: 'Soft Pop',
    colorScheme: 'dark',
    radius: '1rem',
    fontDisplay: "DM Sans, sans-serif",
    fontBody: "DM Sans, sans-serif",
    vars: {
      '--background': '#000000',
      '--foreground': '#ffffff',
      '--card': '#1a212b',
      '--card-foreground': '#ffffff',
      '--popover': '#1a212b',
      '--popover-foreground': '#ffffff',
      '--primary': '#818cf8',
      '--primary-foreground': '#000000',
      '--secondary': '#2dd4bf',
      '--secondary-foreground': '#000000',
      '--muted': '#333333',
      '--muted-foreground': '#cccccc',
      '--accent': '#fcd34d',
      '--accent-foreground': '#000000',
      '--destructive': '#f87171',
      '--border': '#545454',
      '--input': '#ffffff',
      '--ring': '#818cf8',
    },
    lightVars: {
      '--background': '#f7f9f3',
      '--foreground': '#000000',
      '--card': '#ffffff',
      '--card-foreground': '#000000',
      '--popover': '#ffffff',
      '--popover-foreground': '#000000',
      '--primary': '#4f46e5',
      '--primary-foreground': '#ffffff',
      '--secondary': '#14b8a6',
      '--secondary-foreground': '#ffffff',
      '--muted': '#f0f0f0',
      '--muted-foreground': '#333333',
      '--accent': '#f59e0b',
      '--accent-foreground': '#000000',
      '--destructive': '#ef4444',
      '--border': '#000000',
      '--input': '#737373',
      '--ring': '#a5b4fc',
    },
  },
  {
    id: 'sage-garden',
    name: 'Sage Garden',
    colorScheme: 'dark',
    radius: '0.625rem',
    fontDisplay: "'Inter Variable', -apple-system, system-ui, sans-serif",
    fontBody: "'Inter Variable', -apple-system, system-ui, sans-serif",
    vars: {
      '--background': '#0a0a0a',
      '--foreground': '#f5f5f5',
      '--card': '#121212',
      '--card-foreground': '#f5f5f5',
      '--popover': '#121212',
      '--popover-foreground': '#f5f5f5',
      '--primary': '#7c9082',
      '--primary-foreground': '#000000',
      '--secondary': '#1a1a1a',
      '--secondary-foreground': '#f5f5f5',
      '--muted': '#1a1a1a',
      '--muted-foreground': '#a0a0a0',
      '--accent': '#36443a',
      '--accent-foreground': '#f5f5f5',
      '--destructive': '#ef4444',
      '--border': '#2a2a2a',
      '--input': '#121212',
      '--ring': '#7c9082',
    },
    lightVars: {
      '--background': '#f8f7f4',
      '--foreground': '#1a1f2e',
      '--card': '#ffffff',
      '--card-foreground': '#1a1f2e',
      '--popover': '#ffffff',
      '--popover-foreground': '#1a1f2e',
      '--primary': '#7c9082',
      '--primary-foreground': '#ffffff',
      '--secondary': '#ced4bf',
      '--secondary-foreground': '#1a1f2e',
      '--muted': '#e8e6e1',
      '--muted-foreground': '#6b7280',
      '--accent': '#bfc9bb',
      '--accent-foreground': '#1a1f2e',
      '--destructive': '#c73e3a',
      '--border': '#e8e6e1',
      '--input': '#ffffff',
      '--ring': '#7c9082',
    },
  },
]
